name: transmission
description: Flutter package to talk to a Transmission torrent instance
version: 0.1.1
homepage: https://github.com/mylisabox/transmission

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'

dev_dependencies:
